version: "3.9"
services:
  docker:
    build: .
    volumes:
      - type: bind
        source: ./src
        target: /app/src
        read_only: false
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    tty: true